const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('overlay', {
  onSettings: (cb) => ipcRenderer.on('settings', (_e, s) => cb(s)),
  onLockState: (cb) => ipcRenderer.on('lock-state', (_e, locked) => cb(locked)),
  updateSettings: (partial) => ipcRenderer.send('update-settings', partial),
  toggleLock: () => ipcRenderer.send('toggle-lock'),
  minimizeOverlay: () => ipcRenderer.send('minimize-overlay'),
  onHotkeyWarn: (cb) => ipcRenderer.on('hotkey-warn', (_e, keys) => cb(keys)),
  resizeWindow: (w, h) => ipcRenderer.send('resize-window', { width: w, height: h }),
  chooseLog: () => ipcRenderer.invoke('choose-log'),
  clearLog: () => ipcRenderer.invoke('clear-log'),
  logSize: () => ipcRenderer.invoke('log-size'),
  scanLogs: () => ipcRenderer.invoke('scan-logs'),
  switchLog: (p) => ipcRenderer.send('switch-log', p),
  onLogLines: (cb) => ipcRenderer.on('log-lines', (_e, lines) => cb(lines)),
  onLogStatus: (cb) => ipcRenderer.on('log-status', (_e, st) => cb(st)),
  recordKill: (mob, zone) => ipcRenderer.send('record-kill', { mob, zone }),
  recordMobStats: (entries) => ipcRenderer.send('record-mob-stats', entries),
  recordDrop: (mob, item, zone) => ipcRenderer.send('record-drop', { mob, item, zone }),
  getLootDB: () => ipcRenderer.invoke('get-loot-db'),
  onLootDB: (cb) => ipcRenderer.on('loot-db', (_e, db) => cb(db)),
  setInteractive: (v) => ipcRenderer.send('set-interactive', v),
  getZoneData: (zone) => ipcRenderer.invoke('get-zone-data', zone),
  updateZoneData: (zone, aliases) => ipcRenderer.invoke('update-zone-data', zone, aliases),
  getItemData: (name) => ipcRenderer.invoke('get-item-data', name),
  updateItemData: (name) => ipcRenderer.invoke('update-item-data', name),
  searchLocal: (q) => ipcRenderer.invoke('search-local', q),
  searchWiki: (q) => ipcRenderer.invoke('search-wiki', q),
  checkUpdates: () => ipcRenderer.invoke('check-updates'),
  getMap: (short) => ipcRenderer.invoke('get-map', short),
  chooseMapsFolder: () => ipcRenderer.invoke('choose-maps-folder'),
  downloadLegendsMaps: () => ipcRenderer.invoke('download-legends-maps'),
  mapsStatus: () => ipcRenderer.invoke('maps-status'),
  listMaps: () => ipcRenderer.invoke('list-maps'),
  learnZoneMap: (longName, shortName) => ipcRenderer.send('learn-zonemap', { longName, shortName }),
  getZoneMap: () => ipcRenderer.invoke('get-zonemap'),
  learnRespawn: (zone, mob, seconds) => ipcRenderer.send('learn-respawn', { zone, mob, seconds }),
  getRespawns: () => ipcRenderer.invoke('get-respawns'),
  setSourceClass: (source, cls) => ipcRenderer.send('set-source-class', { source, cls }),
  getSourceClasses: () => ipcRenderer.invoke('get-source-classes'),
  learnPet: (name) => ipcRenderer.send('learn-pet', name),
  getPets: () => ipcRenderer.invoke('get-pets'),
  unlearnPet: (name) => ipcRenderer.send('unlearn-pet', name),
  learnSpellClass: (spell, cls) => ipcRenderer.send('learn-spell-class', { spell, cls }),
  getSpellClasses: () => ipcRenderer.invoke('get-spell-classes'),
  learnFadeLabel: (noun, spell) => ipcRenderer.send('learn-fade-label', { noun, spell }),
  getFadeLabels: () => ipcRenderer.invoke('get-fade-labels'),
  wikiSubmit: (payload) => ipcRenderer.invoke('wiki-submit', payload),
  appVersion: () => ipcRenderer.invoke('app-version'),
  onWikiSubmitProgress: (cb) => ipcRenderer.on('wiki-submit-progress', (_e, p) => cb(p)),
  setPhLinks: (zone, camp, phs) => ipcRenderer.send('set-ph-links', { zone, camp, phs }),
  getPhLinks: () => ipcRenderer.invoke('get-ph-links'),
  chooseDataFolder: () => ipcRenderer.invoke('choose-data-folder'),
  dataDirStatus: () => ipcRenderer.invoke('data-dir-status'),
  onSharedReload: (cb) => ipcRenderer.on('shared-reload', () => cb()),
  getSyncFiles: () => ipcRenderer.invoke('get-sync-files'),
  addSyncFile: () => ipcRenderer.invoke('add-sync-file'),
  removeSyncFile: (p) => ipcRenderer.send('remove-sync-file', p),
  syncGameFiles: () => ipcRenderer.invoke('sync-game-files'),
  onGamefilesSynced: (cb) => ipcRenderer.on('gamefiles-synced', (_e, r) => cb(r)),
  onMapsProgress: (cb) => ipcRenderer.on('maps-progress', (_e, p) => cb(p)),
  onTestTab: (cb) => ipcRenderer.on('test-tab', (_e, tab) => cb(tab)),
  closeApp: () => ipcRenderer.send('close-app')
});
